#!/usr/bin/env python3
"""Regenerate measurements/base-depth/README.md and DISCLOSURE.md from this run's artifacts.

Why this file exists (SPEC-base-disclosure-2026-10-07.md):
  * README.md and DISCLOSURE.md claim, in prose, to be produced from the JSON in the directory.
    A claim nobody checks is not a property, so `code/check_published.py` (criterion H) re-runs
    this generator into a temporary directory and compares byte for byte. That is only possible
    if this generator writes *only* what the inputs say.
  * Therefore: **no clock value may enter the output.** An artifact that embeds its own
    generation time cannot be reproduced by anyone, which defeats the entire point of calling it
    generated. The date that appears in DISCLOSURE.md is `provable_until.window_measured_utc`,
    which comes from the input data and is marked `derived`.
  * There is no chain access here and no arithmetic on prices: every number is read from the
    artifacts. The bounds already live in base-depth-panelb-Y.json.

Usage:
    base_depth_publish.py --from base-ladder-Y.json --out-dir <dir>
`--out-dir` is mandatory so that the generator can be pointed at a scratch directory; a run that
can only write in place would make the check above into a second generator.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

CANON_DEFAULT = "basedepth-v3-1"


class InputError(Exception):
    """An input that is missing or does not say what the template quotes from it."""


def load(path, what):
    if not os.path.isfile(path):
        raise InputError(f"missing {what}: {path}")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def need(obj, key, where):
    """Fetch a key or fail loudly. No silent defaults: a missing key must stop the run."""
    if not isinstance(obj, dict) or key not in obj:
        raise InputError(f"{where}: key {key!r} is absent")
    return obj[key]


def short(addr, keep=8):
    s = str(addr)
    return s if len(s) <= keep + 2 else s[: keep + 2] + "…"


def render_errors_table(errors_detail):
    out = ["", "  | pool | size | run 1 | run 2 |", "  |---|---|---|---|"]
    for e in errors_detail:
        out.append("  | `{}` | {} | {} | {} |".format(
            short(need(e, "pool", "errors_detail")),
            need(e, "size", "errors_detail"),
            need(e, "run1", "errors_detail"),
            need(e, "run2", "errors_detail")))
    return "\n".join(out) + "\n"


def write_readme(out_dir, pub, bounds):
    pa = [r for r in need(pub, "publishable_rows", "publishable")
          if not r.get("sentinel_hit")]
    both_ok = need(pub, "both_ok", "publishable")
    errors = need(pub, "errors", "publishable")
    L = ["# Base exit-depth\n\n",
         "_Generated by `code/base_depth_publish.py` from the artifacts in this directory. Every "
         "number in this file is counted from the JSON; none is typed by hand._\n\n",
         "- **Pinned block:** `{}` (`{}`), reads pinned by block hash with `requireCanonical`\n"
         .format(need(pub, "block", "publishable"), need(pub, "block_hash", "publishable")),
         "- **Row set {}:** {} rows · **{} rows read cleanly in both of two independent runs and "
         "were identical across them (0 disagreements)** · {} rows failed to read in at least one "
         "run and are recorded as having no number\n".format(
             need(pub, "block", "publishable"), both_ok + errors, both_ok, errors),
         "- **Publishable {}** — Panel A {} (claim: the measured curve) · Panel B {} (claim: the "
         "on-chain holdings bound) — sealed {}\n\n".format(
             need(pub, "publishable", "publishable"), need(pub, "panel_a", "publishable"),
             need(pub, "panel_b", "publishable"), need(pub, "sealed", "publishable")),
         "## Panel A — the input was fully absorbed inside the current liquidity range\n\n",
         "| pool | size | recovery % | band | fee |\n|---|---|---|---|---|\n"]
    for r in pa:
        L.append("| {} | {} | {} | {} | {} |\n".format(
            need(r, "label", "row"), need(r, "size", "row"), need(r, "recovery_pct", "row"),
            need(r, "band", "row"), r.get("fee")))
    L.append("\n## Panel B — the claim is the on-chain holdings bound, not the walk\n\n")
    L.append("| pool | size | walk % (shown, not the claim) | **upper bound % (holdings)** | "
             "walk ≤ bound | fee |\n|---|---|---|---|---|---|\n")
    for r in bounds:
        L.append("| {} | {} | {} | **{}** | {} | {} |\n".format(
            need(r, "label", "bound"), need(r, "size", "bound"),
            need(r, "recovery_pct", "bound"), need(r, "upper_bound_pct", "bound"),
            "yes" if r.get("walk_within_bound") else "NO", r.get("fee")))
    L.append("\n## Rows excluded in this run (no number published)\n\n")
    L.append("| pool | size | run1 | run2 |\n|---|---|---|---|\n")
    for e in need(pub, "errors_detail", "publishable"):
        L.append("| {} | {} | {} | {} |\n".format(
            need(e, "pool", "errors_detail"), need(e, "size", "errors_detail"),
            need(e, "run1", "errors_detail"), need(e, "run2", "errors_detail")))
    L.append("\nCounts are this run's result, not a property of the measurement; a different block "
             "yields a different row set. Method disclosure, and the history of the superseded "
             "2026-10-04 table, are in DISCLOSURE.md and HISTORY.md.\n")
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(L))


DISCLOSURE_TEMPLATE = """# Disclosure — Base exit-depth

**Canon `{canon}` at pinned block `{block}`**, block hash
`{block_hash}`, reads pinned by that hash with `requireCanonical`. No date appears in this
file on purpose: the hash is the time anchor, and anyone can resolve it with
`eth_getBlockByHash` rather than trusting a date copied in here. The endpoint read was
`{endpoint}`.

## What this run established

- **{both_ok} of {row_set} rows** read cleanly in both of two independent runs and were
  **identical across them**, with **0 disagreements**. Rows that were not identical in both
  runs are not published.
- **{publishable} rows are publishable** — Panel A {panel_a} (claim: the measured curve),
  Panel B {panel_b} (claim: the on-chain holdings bound). **{sealed} rows are sealed.**
- A failed read raises instead of returning a default, and every read failure is recorded per
  (pool, size, fee, spacing, leg, selector).

## What this run did not establish

- **{errors} rows have no figure.** Those rows issue the most reads and failed with
  HTTP 429 on `tickBitmap(int16)` in each run, and the two runs lost different rows. Their
  absence is a property of our read budget in that run, not of the pool. The rows:
{errors_table}- **Two runs agreeing on the same block hash cannot exclude a deterministic degradation.** A
  fallback triggered by load would make both runs give the same answer. Excluding it needs a
  check that does not depend on the endpoint agreeing with itself — a storage proof anchored
  to the block hash — and that has not been done.
- **Multi-range accumulation is not replay-validated** (`multi_cross_validated`:
  `{multi_cross_validated}`), and **the round-trip composition is not replay-validated**
  (`roundtrip_composition_validated`: `{roundtrip_composition_validated}`). Each leg was
  checked separately against real swaps; their composition was not. Rows depending on either
  are sealed rather than published.
- Termination reasons (`exhausted` / `iteration_cap` / `sentinel`) are recorded per row. They
  are a boundary of the method, never a property of the asset.

## Funding

{funded_by}. Refused, in advance rather than on request: {refused}. {if_funded}

Licence: {licence}

## Provable window

`{provable_chain}`, about `{provable_window_blocks}` blocks, measured
`{provable_measured}` and marked derived. Verifying anything older than that window needs an
archival endpoint.

---

Earlier statements about this measurement, what was superseded and why, and one promise that
was made and not kept, are in [HISTORY.md](HISTORY.md). Nothing in this file is history: it
describes the current run only. Instrument properties measured on a different run pair are in
[INSTRUMENT.md](INSTRUMENT.md).
"""

INSTRUMENT_TEMPLATE = """# Instrument properties — Base exit-depth

This file describes the **instrument**, not the asset, and it belongs to the run pair named below.
The scope line is printed from the input rather than written here, so it cannot be dropped in a
later rewrite.

> {scope}

- Block `{block}` · run pair `{run_a}` / `{run_b}` · rows in R (completed and bit-identical in both): **{r_size}**
- **Non-memo row-attributed reads are the reproducible quantity: `{non_memo}` in both runs.**
  Memoisation takes it to `{memo_a}` / `{memo_b}` ({pct_a}% / {pct_b}% fewer).
- On the two selectors `ranges_of` issues ({sel_a}, {sel_b}) the ratio is **{ratio_a}× / {ratio_b}×**,
  and every cache hit lies on those two selectors (`{hits_a}` / `{hits_b}`).
- One row's issued/hit split differs between the runs: `{diff_row}` by {diff_calls} calls — the row
  that failed in one run completed in the other, its crossings matched, so the same memo key was
  filled by one and hit by the other. The split therefore follows cross-row cache fill order; the
  total does not move.
"""


def write_instrument(out_dir, memo):
    """Render INSTRUMENT.md from memo-check.json. Every value comes from the input; none is typed."""
    with open(os.path.join(out_dir, "INSTRUMENT.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(INSTRUMENT_TEMPLATE.format(
            scope=need(memo, "scope", "memo-check"),
            block=need(memo, "block", "memo-check"),
            run_a=need(memo, "run_a", "memo-check"),
            run_b=need(memo, "run_b", "memo-check"),
            r_size=need(memo, "r_size", "memo-check"),
            non_memo=need(memo, "non_memo_reads", "memo-check"),
            memo_a=need(memo, "memo_reads_run_a", "memo-check"),
            memo_b=need(memo, "memo_reads_run_b", "memo-check"),
            pct_a=f"{100.0 * need(memo, 'saved_run_a', 'memo-check') / (need(memo, 'memo_reads_run_a', 'memo-check') + need(memo, 'saved_run_a', 'memo-check')):.1f}",
            pct_b=f"{100.0 * need(memo, 'saved_run_b', 'memo-check') / (need(memo, 'memo_reads_run_b', 'memo-check') + need(memo, 'saved_run_b', 'memo-check')):.1f}",
            sel_a=need(memo, "selectors", "memo-check")[0],
            sel_b=need(memo, "selectors", "memo-check")[1],
            ratio_a=need(memo, "ratio_run_a", "memo-check"),
            ratio_b=need(memo, "ratio_run_b", "memo-check"),
            hits_a=need(memo, "cache_hits_run_a", "memo-check"),
            hits_b=need(memo, "cache_hits_run_b", "memo-check"),
            diff_row=need(memo, "differing_row", "memo-check"),
            diff_calls=need(memo, "differing_calls", "memo-check")))


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate base-depth README.md and DISCLOSURE.md")
    ap.add_argument("--from", dest="ladder", default="base-ladder-Y.json",
                    help="ladder artifact, relative to --out-dir")
    ap.add_argument("--out-dir", required=True,
                    help="directory holding the inputs; outputs are written here")
    a = ap.parse_args()
    # 🔴 inputs and outputs are two different directories, and conflating them is what made the
    # check report not_exercised: check H runs this generator with the measurement directory as
    # cwd and passes a *temporary* directory as --out-dir. Reading inputs from --out-dir then
    # looked for them in the temp directory. Inputs are relative to the measurement directory
    # (cwd, as GENERATED.json declares); outputs go where --out-dir points.
    in_dir = os.getcwd()
    out_dir = os.path.abspath(a.out_dir)
    try:
        lad = load(os.path.join(in_dir, a.ladder), "ladder artifact")
        pub = load(os.path.join(in_dir, "base-depth-publishable-Y.json"), "publishable set")
        bounds = load(os.path.join(in_dir, "base-depth-panelb-Y.json"), "Panel B bounds")
        fund = load(os.path.join(in_dir, "FUNDING.json"), "funding declaration")
        prov = need(lad, "provable_until", a.ladder)
        both_ok = need(pub, "both_ok", "publishable")
        errors = need(pub, "errors", "publishable")
        text = DISCLOSURE_TEMPLATE.format(
            canon=lad.get("canon", CANON_DEFAULT),
            block=need(pub, "block", "publishable"),
            block_hash=need(pub, "block_hash", "publishable"),
            endpoint=need(lad, "endpoint", a.ladder),
            both_ok=both_ok, row_set=both_ok + errors,
            publishable=need(pub, "publishable", "publishable"),
            panel_a=need(pub, "panel_a", "publishable"),
            panel_b=need(pub, "panel_b", "publishable"),
            sealed=need(pub, "sealed", "publishable"),
            errors=errors,
            errors_table=render_errors_table(need(pub, "errors_detail", "publishable")),
            multi_cross_validated=str(need(lad, "multi_cross_validated", a.ladder)).lower(),
            roundtrip_composition_validated=str(
                need(lad, "roundtrip_composition_validated", a.ladder)).lower(),
            provable_chain=need(prov, "chain", "provable_until"),
            provable_window_blocks=need(prov, "window_blocks", "provable_until"),
            provable_measured=need(prov, "window_measured_utc", "provable_until"),
            funded_by=need(fund, "funded_by", "FUNDING.json"),
            refused="; ".join(need(fund, "refused", "FUNDING.json")),
            if_funded=need(fund, "if_funded", "FUNDING.json"),
            licence=need(fund, "licence", "FUNDING.json"))
        with open(os.path.join(out_dir, "DISCLOSURE.md"), "w", encoding="utf-8",
                  newline="\n") as fh:
            fh.write(text)
        write_readme(out_dir, pub, bounds)
        write_instrument(out_dir, load(os.path.join(in_dir, "memo-check.json"),
                                      "instrument properties"))
    except InputError as exc:
        print(f"input error: {exc}", file=sys.stderr)
        return 3
    print(f"wrote README.md and DISCLOSURE.md in {out_dir} (inputs from {in_dir})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
