#!/usr/bin/env python3
"""Generate VERIFIABILITY.md from coverage.json.

    python3 code/make_verifiability.py --out-dir .      # write it
    python3 code/make_verifiability.py --check          # exit 1 if the committed file differs

Why generated rather than written: the prose restates the verdicts, and a restatement drifts
from the list it restates. Here the list is coverage.json and the page is derived from it, so
check H holds the page to the data and a hand edit to either one shows up.

No value here comes from the clock. The dates are the as_of fields of the rows.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HEAD = """# Which venues can be verified, and which can only be trusted

_Generated by `code/make_verifiability.py` from [coverage.json](coverage.json). Every verdict
below is a field in that file; none is typed here._

The quantity this project publishes — what a position actually realises on exit — can only be
published where it can be **read from public contract state by anyone, with no account**. That
is not a preference. A figure obtained through an account cannot be rechecked by the reader, so
it cannot carry a priced deliverable, and a figure that is a market maker's momentary quote is
not a reserve that anyone can read at all.

That condition is becoming a property of the permissionless venues rather than an industry
norm. A regulated venue's disclosure is auditable by its regulator, which is not the same thing
as verifiable by a reader. So the useful thing to keep is not an opinion about which venues are
better, but a dated record of which ones can be checked and which ones cannot — and for the
second kind, the structural reason.

"""

TAIL = """
## What this list is not

It is not a ranking, and a verdict of `no` is not a claim that a venue is thin. For the venues
marked `no` I have no depth measurement and cannot obtain one, which is the entire finding:
anyone sizing a limit against such a venue is choosing to trust a figure rather than check one,
and that choice should at least be visible.

Rows marked `announcement` are taken from public announcements and have **not** been
independently verified here. They record that a venue exists and why its depth is not
checkable. They say nothing about its actual depth.

## The rule this file enforces

A venue that names measurement paths must be readable from public state. A venue that is not
must name none, and every directory under `measurements/` is either claimed by a venue row or
listed as not being a venue-depth measurement — so nothing sits in this tree unclassified.
Check K in `code/check_published.py` fails if any of that stops being true.
"""

VERDICT_ORDER = {"yes": 0, "unknown": 1, "no": 2}


def render(cov: dict) -> str:
    rows = sorted(cov["venues"],
                  key=lambda r: (VERDICT_ORDER.get(r["depth_readable_from_public_state"], 9),
                                 r["key"]))
    out = [HEAD]
    out.append("| venue | chain | issuer | readable from public state | as of | source |\n")
    out.append("|---|---|---|---|---|---|\n")
    for r in rows:
        out.append(f"| {r['venue']} | `{r['chain']}` | {r['issuer']} | "
                   f"**{r['depth_readable_from_public_state']}** | {r['as_of']} | "
                   f"{r['source']} |\n")
    out.append("\n")
    for r in rows:
        out.append(f"### {r['venue']} — {r['depth_readable_from_public_state']}\n\n")
        out.append(f"{r['reason'].rstrip('.')}.\n\n")
        if r.get("measurements"):
            paths = ", ".join(f"`{p}`" for p in r["measurements"])
            out.append(f"Published measurements: {paths}\n\n")
        else:
            out.append("No depth figure is published for this venue.\n\n")
    out.append(f"{cov['note']}\n")
    out.append(TAIL)
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    try:
        cov = json.load(open("coverage.json", encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"input error: coverage.json ({exc})", file=sys.stderr)
        return 3
    text = render(cov)
    if a.check:
        try:
            have = open("VERIFIABILITY.md", encoding="utf-8").read()
        except OSError as exc:
            print(f"VERIFIABILITY.md: {exc}", file=sys.stderr)
            return 1
        if have != text:
            n = next((i for i, (x, y) in enumerate(zip(have, text)) if x != y),
                     min(len(have), len(text)))
            print(f"VERIFIABILITY.md is not what coverage.json produces "
                  f"(first difference at character {n})", file=sys.stderr)
            return 1
        print("  ok -- VERIFIABILITY.md matches coverage.json")
        return 0
    out_dir = os.path.abspath(a.out_dir or ".")
    with open(os.path.join(out_dir, "VERIFIABILITY.md"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote VERIFIABILITY.md in {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
