#!/usr/bin/env python3
"""Render two pinned-block ladder runs side by side, without saying anything moved.

    python3 code/make_block_comparison.py --a <ladder>.json --b <ladder>.json --out-dir <dir>
    python3 code/make_block_comparison.py ... --check        # exit 1 if the committed file differs

Why a generator. The sentence this table must not contain is "it got shallower". A ratio
between two blocks reads as a change in depth, and depth is not the only thing that moves a
pool's state: price leaving a position's range lowers active liquidity with nothing withdrawn.
So the table prints what each block answered and marks the mechanism as not adjudicated, and
being generated is what keeps a later hand from tidying that caveat away.

Two things it refuses to let a reader assume:

  Rows present at one block and not the other are printed in their own section with the
  reason, not dropped and not footnoted. A row that is absent is not a row that did not move.

  Where a whole pool is missing from one side, that is stated in the table's own header area,
  because a reader who scans the comparison and sees no line for a pool will otherwise read
  the silence as agreement.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

# Fields that carry the claim. Deliberately not leg*_bal / *_within_bal / publishable /
# capped_reason: those are gate inputs and gate outputs, and a transiently failing balanceOf
# read moves them without moving anything measured. A row whose balance read failed cannot be
# published anyway -- publishable requires both balances to be non-null -- so the gate carries
# that consequence and the comparison does not.
CLAIM = ("recovery_pct", "band", "class", "crossed", "crossed_leg1", "crossed_leg2",
         "ranges_leg1", "ranges_leg2", "sentinel_hit", "exhausted", "termination_reason")


def load_rows(path: str) -> tuple[dict, dict]:
    """Return ({(pool, size): row}, meta)."""
    with open(path, encoding="utf-8") as fh:
        d = json.load(fh)
    out = {}
    pools = sum((v for v in (d.get("panels") or {}).values() if isinstance(v, list)), [])
    for p in pools:
        for r in (p.get("rows") or []):
            row = dict(r)
            row["_pool"] = p.get("pool")
            row["_label"] = p.get("label")
            row["_fee"] = p.get("fee")
            row["_quote"] = p.get("quote")
            out[(str(p.get("pool")), str(r.get("size")))] = row
    meta = {"block": d.get("block"), "block_hash": d.get("block_hash"),
            "canon": d.get("canon"), "endpoint": d.get("endpoint"),
            "read_failures": d.get("read_failures"),
            "pools": {str(p.get("pool")): p.get("label") for p in pools}}
    return out, meta


def short(a: str | None, keep: int = 10) -> str:
    return (a[:keep] + "…") if a and len(a) > keep + 1 else (a or "?")


def render(A: dict, mA: dict, B: dict, mB: dict) -> str:
    # (label, size) is a partial order: the same pool+label appears at several fees, so rows tie,
    # and a tie sorted out of a `set` would follow string-hash order, which Python randomises per
    # process (PYTHONHASHSEED). Appending fee and pool makes the key a total order, so the file
    # does not depend on which process generated it.
    def key(k):
        r = A[k] if k in A else B[k]
        return (r["_label"] or "", float(k[1]), str(r.get("_fee")), str(k[0]))
    both = sorted(set(A) & set(B), key=key)
    only_a = sorted(set(A) - set(B), key=key)
    only_b = sorted(set(B) - set(A), key=key)
    pools_only_a = sorted(set(mA["pools"]) - set(mB["pools"]))
    pools_only_b = sorted(set(mB["pools"]) - set(mA["pools"]))

    L = ["# Two pinned blocks, side by side\n\n",
         "_Generated by `code/make_block_comparison.py` from the two ladder artifacts named "
         "below. Every figure is read from them; none is typed here._\n\n",
         f"- **Block A** `{mA['block']}` · `{mA['block_hash']}`\n",
         f"- **Block B** `{mB['block']}` · `{mB['block_hash']}`\n",
         f"- Rows at both blocks: **{len(both)}** · only at A: **{len(only_a)}** · "
         f"only at B: **{len(only_b)}**\n\n"]

    L.append("**What this table does not say.** It prints what each block answered. It does "
             "not say depth changed. A pool's active liquidity falls when price leaves a "
             "position's range with nothing withdrawn, so a difference here is consistent "
             "with withdrawal, with a price move, and with a reweighting, and this table "
             "adjudicates between none of them. **Mechanism: not adjudicated.**\n\n")

    if pools_only_a or pools_only_b:
        L.append("## Coverage is not the same at both blocks\n\n")
        L.append("This is in the table rather than in a footnote, because a reader who finds "
                 "no line for a pool will otherwise read the silence as agreement.\n\n")
        for keys, where, other in ((pools_only_a, "A", "B"), (pools_only_b, "B", "A")):
            for pool in keys:
                lab = (mA if where == "A" else mB)["pools"].get(pool)
                L.append(f"- **{lab}** (`{short(pool, 14)}`) has rows at block {where} and "
                         f"**none at block {other}**. Nothing in this table speaks to that "
                         f"pool at block {other}.\n")
        L.append("\n")

    L.append("## Rows answered at both blocks\n\n")
    L.append("| pool | fee | size | recovery % at A | recovery % at B | difference (pp) | "
             "band A | band B | claim fields identical |\n")
    L.append("|---|---|---|---|---|---|---|---|---|\n")
    for k in both:
        a, b = A[k], B[k]
        same = all(str(a.get(f)) == str(b.get(f)) for f in CLAIM)
        # error 行没有 recovery_pct ⇒ 用 .get 并把 KeyError 一起捕住。
        # 差值缺失写 "-",不写 0 —— "没有数" 与 "没有变化" 不是一回事。
        try:
            diff = f"{float(b.get('recovery_pct')) - float(a.get('recovery_pct')):+.6f}"
        except (TypeError, ValueError, KeyError):
            diff = "-"
        L.append(f"| {a['_label']} | {a.get('_fee')} | {k[1]} | {a.get('recovery_pct')} | "
                 f"{b.get('recovery_pct')} | {diff} | {a.get('band')} | {b.get('band')} | "
                 f"{'yes' if same else '**no**'} |\n")
    L.append("\n")

    for keys, src, where, other in ((only_a, A, "A", "B"), (only_b, B, "B", "A")):
        if not keys:
            continue
        L.append(f"## Rows answered at block {where} and not at block {other}\n\n")
        L.append(f"Listed, not dropped: a row that is absent is not a row that did not "
                 f"move.\n\n")
        L.append("| pool | fee | size | recovery % | class | termination |\n")
        L.append("|---|---|---|---|---|---|\n")
        for k in keys:
            r = src[k]
            L.append(f"| {r['_label']} | {r.get('_fee')} | {k[1]} | "
                     f"{r.get('recovery_pct')} | {r.get('class')} | "
                     f"{r.get('termination_reason')} |\n")
        L.append("\n")

    L.append("## What produced each side\n\n")
    for m, name in ((mA, "A"), (mB, "B")):
        L.append(f"- Block {name}: canon `{m.get('canon')}`, endpoint `{m.get('endpoint')}`, "
                 f"read failures recorded in that run: `{m.get('read_failures')}`\n")
    L.append("\nThe fields compared for `claim fields identical` are "
             + ", ".join(f"`{f}`" for f in CLAIM)
             + ". Balance reads, the balance gate and `publishable` are not compared: a "
               "transiently failing `balanceOf` moves them without moving anything measured, "
               "and a row whose balance read failed cannot be published in any case, so the "
               "gate carries that consequence instead of the comparison.\n")
    return "".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", required=True)
    ap.add_argument("--b", required=True)
    ap.add_argument("--out-dir", default=".")
    ap.add_argument("--name", default="COMPARISON.md")
    ap.add_argument("--check", action="store_true")
    g = ap.parse_args()
    try:
        A, mA = load_rows(g.a)
        B, mB = load_rows(g.b)
    except (OSError, ValueError, KeyError) as exc:
        print(f"input error: {exc}", file=sys.stderr)
        return 3
    if not A or not B:
        print("input error: one of the ladders has no rows", file=sys.stderr)
        return 3
    text = render(A, mA, B, mB)
    target = os.path.join(os.path.abspath(g.out_dir), g.name)
    if g.check:
        try:
            have = open(target, encoding="utf-8").read()
        except OSError as exc:
            print(f"{target}: {exc}", file=sys.stderr)
            return 1
        if have != text:
            n = next((i for i, (x, y) in enumerate(zip(have, text)) if x != y),
                     min(len(have), len(text)))
            print(f"{g.name} is not what the ladders produce (first difference at "
                  f"character {n})", file=sys.stderr)
            return 1
        print(f"  ok -- {g.name} matches the two ladder artifacts")
        return 0
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {target}: {len(A & B.keys() if hasattr(A, '__and__') else set(A) & set(B))} "
          f"rows at both blocks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
